<?php

/**
 * Implements hook_node_view().
 */
function quote_fix_node_view($node, $view_mode) {
  if (user_access('post comments') && in_array($node->type, _quote_variable_get('node_types')) && $node->comment == COMMENT_NODE_OPEN && _quote_variable_get('node_link_display')) {
    $links['quote'] = array(
      'title' => t('Quote'),
      'href' => "comment/reply/$node->nid",
      'attributes' => array('title' => t('Quote this post in your reply.'), 'class'=>'af-button-small'),
      'query' => array('quote' => 1),
//      'fragment' => 'comment-form'
    );
    $links['quote']['title'] = '<span>' . $links['quote']['title'] . '</span>';
    $links['quote']['html'] = TRUE;
    $node->content['links']['quote'] = array(
      '#links' => $links,
      '#attributes' => array('class' => array('links', 'inline'))
    );
  }
}

/**
 * Implements hook_comment_view().
 */
function quote_fix_comment_view($comment) {
  if (user_access('post comments')) {
    $node = node_load($comment->nid);
    if (in_array($node->type, _quote_variable_get('node_types')) && $node->comment == COMMENT_NODE_OPEN) {
      $links['quote'] = array(
        'title' => t('Quote'),
        'href' => "comment/reply/$node->nid/$comment->cid",
        'attributes' => array('title' => t('Quote this post in your reply.'), 'class'=>'af-button-small'),
        'query' => array('quote' => 1),
      );
      $links['quote']['title'] = '<span>' . $links['quote']['title'] . '</span>';
      $links['quote']['html'] = TRUE;
      $comment->content['links']['quote'] = array(
        '#links' => $links,
        '#attributes' => array('class' => array('links', 'inline'))
      );
    //  $comment->content['links']['comment']['#links']['post-delete']['attributes']['class'][] = "btn btn-sm btn-danger";
    }
  }
}
